*&---------------------------------------------------------------------*
*& Report YE00_EX029
*&---------------------------------------------------------------------*
*& Class 상속 연습
*&---------------------------------------------------------------------*
REPORT YE03_EX029.

CLASS LCL_HUMAN DEFINITION.
  PUBLIC SECTION.
    METHODS CONSTRUCTOR IMPORTING IV_NAME TYPE STRING.
    METHODS INTRODUCE_ME.

  PROTECTED SECTION.
    DATA MV_NAME TYPE STRING.
ENDCLASS.

CLASS LCL_HUMAN IMPLEMENTATION.
  METHOD CONSTRUCTOR.
    MV_NAME = IV_NAME.
  ENDMETHOD.
  METHOD INTRODUCE_ME.
    WRITE : / '내 이름은', MV_NAME, '입니다.'.
*    WRITE : / '내 이름은', MV_NAME, '이고, 학교는', MV_SCHOOL,'입니다.'.
  ENDMETHOD.
ENDCLASS.

CLASS LCL_STUDENT DEFINITION INHERITING FROM LCL_HUMAN.
  PUBLIC SECTION.
    METHODS CONSTRUCTOR IMPORTING
                          IV_NAME   TYPE STRING
                          IV_SCHOOL TYPE STRING.

    " 부모 클래스의 메소드를 다시 만듦
    METHODS INTRODUCE_ME REDEFINITION.

  PRIVATE SECTION.
    DATA MV_SCHOOL TYPE STRING.
ENDCLASS.

CLASS LCL_STUDENT IMPLEMENTATION.
  METHOD CONSTRUCTOR.
    CALL METHOD SUPER->CONSTRUCTOR
      EXPORTING
        IV_NAME = IV_NAME .
    ME->MV_SCHOOL = IV_SCHOOL.
  ENDMETHOD.
  METHOD INTRODUCE_ME.
    WRITE : / '내 이름은', MV_NAME, '이고, 학교는', MV_SCHOOL,'입니다.'.
  ENDMETHOD.
ENDCLASS.

START-OF-SELECTION.
  DATA LO_HUMAN   TYPE REF TO LCL_HUMAN.
  DATA LO_STUDENT TYPE REF TO LCL_STUDENT.

  CREATE OBJECT LO_HUMAN
    EXPORTING
      IV_NAME = '정훈영'.

  CREATE OBJECT LO_STUDENT
    EXPORTING
      IV_NAME   = '정훈영'
      IV_SCHOOL = '솔고등학교'.

  CALL METHOD LO_HUMAN->INTRODUCE_ME.
  CALL METHOD LO_STUDENT->INTRODUCE_ME.
