*&---------------------------------------------------------------------*
*& Report YE03_EX016
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT YE03_EX016.

DATA GS_SFLIGHT TYPE SFLIGHT.

*SELECT-OPTIONS SO_CARR FOR GS_SFLIGHT-CARRID.
*PARAMETERS: PA_LIM_1 RADIOBUTTON GROUP LIM DEFAULT 'X',
*            PA_LIM_2 RADIOBUTTON GROUP LIM,
*            PA_LIM_3 RADIOBUTTON GROUP LIM.

SELECTION-SCREEN BEGIN OF BLOCK B03.
PARAMETERS PA_CARR TYPE SCARR-CARRID.
SELECTION-SCREEN END OF BLOCK B03.

SELECTION-SCREEN BEGIN OF BLOCK B01 WITH FRAME.
SELECT-OPTIONS SO_CARR FOR GS_SFLIGHT-CARRID.
SELECTION-SCREEN END OF BLOCK B01.

SELECTION-SCREEN BEGIN OF BLOCK B02 WITH FRAME TITLE TEXT-T01. "검색 조건 추가
PARAMETERS: PA_LIM_1 RADIOBUTTON GROUP LIM DEFAULT 'X',
            PA_LIM_2 RADIOBUTTON GROUP LIM,
            PA_LIM_3 RADIOBUTTON GROUP LIM.
SELECTION-SCREEN END OF BLOCK B02.



SELECTION-SCREEN BEGIN OF LINE.

SELECTION-SCREEN COMMENT 1(20) TEXT-S01.
SELECTION-SCREEN COMMENT 30(6) TEXT-S02 FOR FIELD PA_COL.
PARAMETERS PA_COL AS CHECKBOX.

SELECTION-SCREEN COMMENT 40(6) TEXT-S03.
PARAMETERS PA_ICON AS CHECKBOX.
SELECTION-SCREEN END OF LINE.

" 비어있는 3줄 추가
SELECTION-SCREEN SKIP 3.

SELECTION-SCREEN BEGIN OF LINE.
PARAMETERS PA_CON TYPE SPFLI-CONNID.
SELECTION-SCREEN END OF LINE.
