*&---------------------------------------------------------------------*
*& Report YE03_EX007
*&---------------------------------------------------------------------*
*& Structure 변수 연습
*&---------------------------------------------------------------------*
REPORT YE03_EX007.

TYPES: BEGIN OF TS_FLIGHTINFO,
   CARRID TYPE S_CARR_ID,
  CARRNAME TYPE S_CARRNAME,
  CONNID TYPE S_CONN_ID,
  FLDATE TYPE S_DATE,
  PERCENTAGE TYPE P LENGTH 3 DECIMALS 2,

  END OF TS_FLIGHTINFO.

*TYPES  BEGIN OF TS_FLIGHTINFO.
*TYPES   CARRID TYPE S_CARR_ID.
*TYPES CARRNAME TYPE S_CARRNAME.
*TYPES  CONNID TYPE S_CONN_ID.
*TYPES  FLDATE TYPE S_DATE.
*TYPES  PERCENTAGE TYPE P LENGTH 3 DECIMALS 2.
*TYPES  END OF TS_FLIGHTINFO.

DATA GS_FLIGHTINFO TYPE TS_FLIGHTINFO.

GS_FLIGHTINFO-CARRID = 'KA'.
GS_FLIGHTINFO-CARRNAME = '대한항공'.
GS_FLIGHTINFO-CONNID = '1234'.
GS_FLIGHTINFO-FLDATE = '20240101'.
GS_FLIGHTINFO-PERCENTAGE = '97.12'.

WRITE /1 '항공사ID:'.
WRITE 15 GS_FLIGHTINFO-CARRID.

WRITE /1 '항공사명:'.
WRITE 15 GS_FLIGHTINFO-CARRNAME.
*WRITE /1 '항공편:'.
*WRITE 15 GS_FLIGHTINFO-CARRNAME.
*WRITE /1 '항공사명:'.
*WRITE 15 GS_FLIGHTINFO-CARRNAME.
*WRITE /1 '항공사명:'.
*WRITE 15 GS_FLIGHTINFO-CARRNAME.
*WRITE /1 '항공사명:'.
*WRITE 15 GS_FLIGHTINFO-CARRNAME.
