*&---------------------------------------------------------------------*
*& Report ZBC430_E03_COPY_DATA
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZBC430_E03_COPY_DATA.

DATA GT_SCARR TYPE TABLE OF SCARR.
DATA GT_ZCARR TYPE TABLE OF ZCARR_E03.

DATA GT_SPFLI TYPE TABLE OF SPFLI.
DATA GT_ZPFLI TYPE TABLE OF ZSPFLI_E03.

DATA GT_SFLIGHT TYPE TABLE OF SFLIGHT.
DATA GT_ZFLIGHT TYPE TABLE OF ZSFLIGHT_E03.


START-OF-SELECTION.

* Z 테이블의 내용을 초기화(모든 레코드를 전부 삭제)
DELETE FROM ZCARR_E03.
DELETE FROM ZSPFLI_E03.
DELETE FROM ZSFLIGHT_E03.


* S 테이블의 내용을 조회하여 Z 테이블로 복사
SELECT * FROM SCARR INTO TABLE GT_SCARR.    " SCARR의 모든 데이터 조회
* SELECT * FROM SCARR INTO TABLE GT_SCARR WHERE CARRID EQ 'AA'. "AA만 조회
  MOVE-CORRESPONDING GT_SCARR TO GT_ZCARR.  " 필드명이 동일한 데이터 복사
  INSERT ZCARR_E03 FROM TABLE GT_ZCARR.     " ZCARR_E03 에 데이터 신규생성

* S 테이블의 내용을 조회하여 Z 테이블로 복사
SELECT * FROM SPFLI INTO TABLE GT_SPFLI.
  MOVE-CORRESPONDING GT_SPFLI TO GT_ZPFLI.
  INSERT ZSPFLI_E03 FROM TABLE GT_ZPFLI.

* S 테이블의 내용을 조회하여 Z 테이블로 복사
SELECT * FROM SFLIGHT INTO TABLE GT_SFLIGHT.
  MOVE-CORRESPONDING GT_SFLIGHT TO GT_ZFLIGHT.
  INSERT ZSFLIGHT_E03 FROM TABLE GT_ZFLIGHT.
